faults:
  - "HopeConwayOS"
  - "Wairau"
  - "AlpineK2T"
  - "Port2GreyL"
ims:
  - "PGV"
  - "PGV_sigma"
  - "PGA"
  - "PGA_sigma"
  - "pSA_0.1"
  - "pSA_0.1_sigma"
  - "pSA_1.0"
  - "pSA_1.0_sigma"
  - "pSA_5.0"
  - "pSA_5.0_sigma"
max_ranges:
    PGV: "80"
    PGV_sigma: "2.5"
    PGA: "0.8"
    PGA_sigma: "2.5"
    pSA_0.1: "1.5"
    pSA_0.1_sigma: "2.5"
    pSA_1.0: "0.8"
    pSA_1.0_sigma: "2.5"
    pSA_5.0: "0.2"
    pSA_5.0_sigma: "2.5"
srfs:
    HopeConwayOS: "/isilon/cybershake/v20p4/Sources/scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/jpa198/cybershake_sources/Data/Sources/HopeConwayOS/Srf/HopeConwayOS_REL01.srf"
    Wairau: "/isilon/cybershake/v20p4/Sources/scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/jpa198/cybershake_sources/Data/Sources/Wairau/Srf/Wairau_REL01.srf"
    AlpineK2T: "/isilon/cybershake/v20p4/Sources/scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/jpa198/cybershake_sources/Data/Sources/AlpineK2T/Srf/AlpineK2T_REL01.srf"
    Port2GreyL: "/isilon/cybershake/v20p4/Sources/scale_wlg_nobackup/filesets/nobackup/nesi00213/RunFolder/jpa198/cybershake_sources/Data/Sources/Port2GreyL/Srf/Port2GreyL_REL01.srf"
station_file: "/isilon/seistech/sites/20p3/non_uniform_whole_nz_with_real_stations-hh400_v20p3_land.ll"
component: "geom"